name: peatdashboard
description: "Peat"
publish_to: 'Peat-IFCE'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^29.1.33
  provider: ^6.1.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  http: ^1.0.0
  flutter_dotenv: ^5.0.2
  sleek_circular_slider: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: false
  ios: true
  web: true
  color_dark: "#000000"
  image_dark: assets/logo.png


flutter:
  uses-material-design: true
  assets:
    - assets/PeatDeviceLight.png
    - assets/logo.png
    - assets/comedouro_icon.png
    - assets/gato_direita.png
    - assets/gato_esquerda.png
    - assets/.env
    - assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
    - assets/fonts/SFPRODISPLAYREGULAR.OTF
    - assets/fonts/SFPRODISPLAYBOLD.OTF
    - assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
    - assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
    - assets/fonts/SFPRODISPLAYTHINITALIC.OTF
    - assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
    - assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
    - assets/fonts/SFPRODISPLAYMEDIUM.OTF
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
